baseURL = 'https://csunibo.github.io/wiki/'
languageCode = 'it-IT'
title = 'Wiki'
theme = "hugo-theme-relearn"

[module]
[[module.imports]]
  path = 'github.com/McShelby/hugo-theme-relearn'

[outputs]
home = [ "HTML", "RSS", "SEARCH"]
section = ["HTML", "RSS", "PRINT"]
page = ["HTML", "RSS", "PRINT"]

[params]
  editURL = "https://github.com/csunibo/wiki/edit/main/content/"
  description = "Documentation for Hugo Relearn Theme"
  author = "Studenti del corso di laurea in Informatica dell'Università di Bologna"
  showVisitedLinks = true
  collapsibleMenu = true
  disableBreadcrumb = false
  disableInlineCopyToClipBoard = true
  disableNextPrev = false
  disableLandingPageButton = false
  titleSeparator = "::"
  themeVariant = [ "auto", "relearn-bright", "relearn-light", "relearn-dark", "learn", "neon", "blue", "green", "red" ]
  themeVariantAuto = [ "relearn-light", "relearn-dark" ]
  disableSeoHiddenPages = true
  disableLanguageSwitchingButton = true
  mermaidInitialize = "{ \"securityLevel\": \"loose\" }"
  mermaidZoom = true
  additionalContentLanguage = [ "en" ]

[languages]
[languages.en]
landingPageName = "<i class='fas fa-home'></i> Pagina iniziale"
